# enable or disable logging
log: 1

# logging settings
log4perl:
  # default logging, log to syslog only.
  default: |
    log4perl.rootLogger                = DEBUG, SYSLOG
    log4perl.appender.SYSLOG           = Log::Dispatch::Syslog
    log4perl.appender.SYSLOG.min_level = debug
    log4perl.appender.SYSLOG.ident     = Nagios::Nrpe
    log4perl.appender.SYSLOG.facility  = daemon
    log4perl.appender.SYSLOG.layout    = Log::Log4perl::Layout::SimpleLayout

  # verbose logging, log to syslog and stdout.
  verbose: |
    log4perl.rootLogger                = DEBUG, SYSLOG, SCREEN
    log4perl.appender.SCREEN         = Log::Log4perl::Appender::Screen
    log4perl.appender.SCREEN.stderr  = 0
    log4perl.appender.SCREEN.layout  = Log::Log4perl::Layout::PatternLayout
    log4perl.appender.SCREEN.layout.ConversionPattern = %d %p %m %n
    log4perl.appender.SYSLOG           = Log::Dispatch::Syslog
    log4perl.appender.SYSLOG.min_level = debug
    log4perl.appender.SYSLOG.ident     = Nagios::Nrpe
    log4perl.appender.SYSLOG.facility  = daemon
    log4perl.appender.SYSLOG.layout    = Log::Log4perl::Layout::SimpleLayout

  # disabled logging (/dev/null), effectively killing all logging.
  disabled: |
    log4perl.rootLogger              = DEBUG, LOG1
    log4perl.appender.LOG1           = Log::Log4perl::Appender::File
    log4perl.appender.LOG1.filename  = /dev/null
    log4perl.appender.LOG1.mode      = append
    log4perl.appender.LOG1.layout    = Log::Log4perl::Layout::PatternLayout
    log4perl.appender.LOG1.layout.ConversionPattern = %d %p %m %n

# base template for new nrpe checks.
template: |
  #!/usr/bin/env perl

  use warnings;
  use strict;

  use Nagios::Nrpe;
  use Getopt::Long;
  use Pod::Usage;

  my $opts = { verbose => 0 };
  GetOptions( $opts, 'verbose|v', 'help|h', 'man|m' );

  my $nrpe = Nagios::Nrpe->new( verbose => $opts->{verbose} );


  __END__

  =head1 NAME

  B<[% checkname %]l> - INSERT INFO HERE.

  =head1 SYNOPSIS

  =head2 Available Options

   <[% checkname %] --verbose <prints info to stdout> --help <prints help> --man <prints full man page>

  =head1 OPTIONS

  =over 8

  =item B<-v, --verbose>
   Prints the output from $nrpe->info(), $nrpe->debug() and $nrpe->error() to
   stdout.

  =item B<-h, --help>
   Prints a brief help message from this script.

  =item B<-m, --man>
   Prints the full manual page from this script.

  =back

  =head1 DESCRIPTION

  INSERT YOUR DESCRIPTION HERE.

  =head1 AUTHOR

  INSERT AUTHOR NAME, C<< < INSERT AUTHOR EMAIL > >>

  =cut
