---
abstract: "A small framework for custom Nagios NRPE client side checks. \nThe main objective of these modules is to remove the repetitive boilerplate\nrequired when making client side NRPE checks without hopefully adding in too\nmany dependencies."
author:
  - 'Sarah Fuller <sarah@averna.id.au>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Nagios-Nrpe
requires:
  Carp: 0
  Moo: 0
  Moo::Role: 0
version: 0.001
